--- Makefile	2025-11-16 15:20:35.413674789 +0100
+++ Makefile.new	2025-11-16 15:21:23.829928376 +0100
@@ -39,7 +39,7 @@
 
 #!cmsCFLAGS=`cat ../cflags` 
 #CFLAGS= -Aa
-CFLAGS= 
+CFLAGS= -Wno-implicit-function-declaration
 CLFLAGS = -lm
 
 all: kpp
