# Copyright (c) 2025 LATMOS (France, UMR 8190) and IGE (France, UMR 5001).
#
# License: BSD 3-clause "new" or "revised" license (BSD-3-Clause).

name: Quality controls for Python code
run-name: Run quality controls for Python code
on:
  workflow_dispatch:
  push:
  pull_request:
    paths:
      - '**.py'
jobs:
  Run-Quality-Controls:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Prepare Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle ruff
      - name: Run checkers and linters
        run: |
          pycodestyle ${{ github.workspace }}/postprocess
          ruff check  --diff ${{ github.workspace }}/postprocess
          ruff format --diff ${{ github.workspace }}/postprocess
