# Copyright (c) 2025 LATMOS (France, UMR 8190) and IGE (France, UMR 5001).
#
# License: BSD 3-clause "new" or "revised" license (BSD-3-Clause).

name: Ruff
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.py'
jobs:
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Prepare Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "--version"
      - name: Run Ruff (check)
        run: ruff check --diff data postprocess
      - name: Run Ruff (format)
        run: ruff format --diff data postprocess
